name: "Update Upstream"

on:
  workflow_call:
    inputs:
      packages:
        type: string
        description: "The packages to update"
        required: true
      no-update:
        type: boolean
        description: "Skip updating dependencies"
        required: false

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        id: app-token
        with:
          app-id: ${{ vars.WASILIBS_APP_ID }}
          private-key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v3
        with:
          package_json_file: buildtools/wasm/package.json

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          cache: pnpm
          cache-dependency-path: buildtools/wasm/pnpm-lock.yaml

      - name: Update upstream
        run: pnpm up --latest ${{ inputs.packages }}
        working-directory: buildtools/wasm

      - run: git diff --exit-code
        id: check-diff
        continue-on-error: true

      - name: Update dependencies
        if: steps.check-diff.outcome == 'failure' && !inputs.no-update
        run: pnpm up --latest
        working-directory: buildtools/wasm

      - run: go run ./build wasm
        if: steps.check-diff.outcome == 'failure'

      - uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1
        if: steps.check-diff.outcome == 'failure'
        with:
          subject-path: internal/wasm/*.wasm

      - name: build and create PR
        if: steps.check-diff.outcome == 'failure'
        run: |
          BOT_USER_ID=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)
          git config --global user.name '${{steps.app-token.outputs.app-slug}}[bot]'
          git config --global user.email '${BOT_USER_ID}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
          git checkout -b update-upstream-${{ github.run_id }}
          git add .
          git commit -m "Update to latest upstream"
          git push -u origin -f update-upstream-${{ github.run_id }}
          gh pr create --fill --head update-upstream-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
