name: "Update Upstream"

on:
  workflow_call:
    inputs:
      packages:
        type: string
        description: "The packages to update"
        required: true
      no-update:
        type: boolean
        description: "Skip updating dependencies"
        required: false

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v1
        id: app-token
        with:
          app-id: ${{ vars.WASILIBS_APP_ID }}
          private-key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: buildtools/wasm/package.json

      - name: Update upstream
        run: |
          bun update --latest ${{ inputs.packages }}
          # https://github.com/oven-sh/bun/issues/13388
          bun install
        working-directory: buildtools/wasm

      - run: git diff --exit-code
        id: check-diff
        continue-on-error: true

      - name: Update dependencies
        if: steps.check-diff.outcome == 'failure' && !inputs.no-update
        run: |
          bun update --latest
          bun install
        working-directory: buildtools/wasm

      - run: go run ./build wasm
        if: steps.check-diff.outcome == 'failure'

      - uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v1
        if: steps.check-diff.outcome == 'failure'
        with:
          subject-path: internal/wasm/*.wasm

      - name: build and create PR
        if: steps.check-diff.outcome == 'failure'
        run: |
          git config --global user.name '${{steps.app-token.outputs.app-slug}}[bot]'
          git config --global user.email '173422847+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
          git checkout -b update-upstream-${{ github.run_id }}
          git add .
          git commit -m "Update to latest upstream"
          git push -u origin -f update-upstream-${{ github.run_id }}
          gh pr create --fill --head update-upstream-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
