name: "Update Upstream"

on:
  workflow_call:
    inputs:
      packages:
        type: string
        description: "The packages to update"
        required: true

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: ${{ vars.WASILIBS_APP_ID }}
          private-key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v3
        with:
          package_json_file: buildtools/wasm/package.json

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache: pnpm
          cache-dependency-path: buildtools/wasm/pnpm-lock.yaml

      - name: Update upstream
        run: pnpm up --latest ${{ inputs.packages }}
        working-directory: buildtools/wasm

      - run: git diff --exit-code
        id: check-diff
        continue-on-error: true

      - name: Update dependencies
        if: steps.check-diff.outcome == 'failure'
        run: pnpm up --latest
        working-directory: buildtools/wasm

      - run: go run ./build wasm
        if: steps.check-diff.outcome == 'failure'

      - uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1
        if: steps.check-diff.outcome == 'failure'
        with:
          subject-path: internal/wasm/*.wasm

      - name: build and create PR
        if: steps.check-diff.outcome == 'failure'
        run: |
          BOT_USER_ID=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)
          git config --global user.name '${{steps.app-token.outputs.app-slug}}[bot]'
          git config --global user.email '${BOT_USER_ID}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
          git checkout -b update-upstream-${{ github.run_id }}
          git add .
          git commit -m "Update to latest upstream"
          git push -u origin -f update-upstream-${{ github.run_id }}
          gh pr create --fill --head update-upstream-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
