name: "Update Upstream"

on:
  workflow_call:
    inputs:
      packages:
        type: string
        description: "The packages to update"
        required: true

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.WASILIBS_APP_ID }}
          private-key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - uses: pnpm/action-setup@v3
        with:
          package_json_file: buildtools/wasm/package.json

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: buildtools/wasm/pnpm-lock.yaml

      - name: Update upstream
        run: pnpm up --latest ${{ inputs.packages }}
        working-directory: buildtools/wasm

      - run: git diff --exit-code
        id: check-diff
        continue-on-error: true

      - name: Update dependencies
        if: steps.check-diff.outcome == 'failure'
        run: pnpm up --latest
        working-directory: buildtools/wasm

      - run: go run ./build wasm
        if: steps.check-diff.outcome == 'failure'

      - name: build and create PR
        if: steps.check-diff.outcome == 'failure'
        run: |
          git config --global user.name '${{steps.app-token.outputs.app-slug}}[bot]'
          git config --global user.email '173422847+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
          git checkout -b update-upstream-${{ github.run_id }}
          git add .
          git commit -m "Update to latest upstream"
          git push -u origin -f update-upstream-${{ github.run_id }}
          gh pr create --fill --head update-upstream-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
