name: "Update Upstream"

on:
  workflow_call:
    inputs:
      packages:
        type: string
        description: "The packages to update"
        required: true
      no-update:
        type: boolean
        description: "Skip updating dependencies"
        required: false

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@67e27a7eb7db372a1c61a7f9bdab8699e9ee57f7 # v1.11.3
        id: app-token
        with:
          app-id: ${{ vars.WASILIBS_APP_ID }}
          private-key: ${{ secrets.WASILIBS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: curioswitch/go-build/.github/actions/setup-go@7489f72867246693fc1cc65560c68cdc860a1f8a # v0.5.2

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version-file: buildtools/wasm/package.json

      - name: Update upstream
        run: |
          bun update --latest ${{ inputs.packages }}
          # https://github.com/oven-sh/bun/issues/13388
          bun install
        working-directory: buildtools/wasm

      - run: git diff --exit-code
        id: check-diff
        continue-on-error: true

      - name: Update dependencies
        if: steps.check-diff.outcome == 'failure' && !inputs.no-update
        run: |
          bun update --latest
          bun install
        working-directory: buildtools/wasm

      - run: go run ./build wasm
        if: steps.check-diff.outcome == 'failure'

      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        if: steps.check-diff.outcome == 'failure'
        with:
          subject-path: internal/wasm/*.wasm

      - name: build and create PR
        if: steps.check-diff.outcome == 'failure'
        run: |
          git config --global user.name '${{steps.app-token.outputs.app-slug}}[bot]'
          git config --global user.email '173422847+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
          git checkout -b update-upstream-${{ github.run_id }}
          git add .
          git commit -m "Update to latest upstream"
          git push -u origin -f update-upstream-${{ github.run_id }}
          gh pr create --fill --head update-upstream-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
